# Generated by Django 2.1.3 on 2019-05-28 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
