# Generated by Django 2.1.3 on 2019-05-28 11:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 28, 11, 17, 37, 79840, tzinfo=utc)),
        ),
    ]
